# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bsts_posterior_predict <- function(model, Z, G, Q, R, init_state, X, B, gpriors, qpriors, vpriors, U) {
    .Call(`_tsforeign_bsts_posterior_predict`, model, Z, G, Q, R, init_state, X, B, gpriors, qpriors, vpriors, U)
}

